# Generated by Django 4.2.7 on 2025-07-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('microchip_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='PetRegistrationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='active', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('expected_images_count', models.IntegerField(default=10)),
                ('actual_images_count', models.IntegerField(default=0)),
                ('capture_duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_sessions', to='pets.pet')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PetMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('checkup', 'Checkup'), ('treatment', 'Treatment'), ('surgery', 'Surgery'), ('medication', 'Medication')], max_length=20)),
                ('date', models.DateField()),
                ('veterinarian', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('image_type', models.CharField(choices=[('registration', 'Registration'), ('verification', 'Verification'), ('profile', 'Profile')], default='registration', max_length=20)),
                ('quality_status', models.CharField(choices=[('pending', 'Pending'), ('good', 'Good'), ('poor', 'Poor'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('detected_pet_type', models.CharField(blank=True, max_length=20, null=True)),
                ('detection_confidence', models.FloatField(blank=True, null=True)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('blur_score', models.FloatField(blank=True, null=True)),
                ('brightness_score', models.FloatField(blank=True, null=True)),
                ('contrast_score', models.FloatField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.petregistrationsession')),
            ],
            options={
                'ordering': ['sequence_number', 'captured_at'],
            },
        ),
    ]
