# Generated by Django 4.2.7 on 2025-07-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_vector', models.JSONField()),
                ('embedding_model', models.CharField(default='clip-ViT-B-32', max_length=100)),
                ('vector_dimension', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_images_count', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('confidence_level', models.CharField(choices=[('eagle_trail', 'Eagle Trail'), ('lobo_trail', 'Lobo Trail'), ('no_match', 'No Match')], max_length=20)),
                ('result_type', models.CharField(choices=[('registration', 'Registration'), ('verification', 'Verification'), ('search', 'Search')], default='search', max_length=20)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('matched_embedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_results', to='face_recognition.faceembedding')),
                ('matched_pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognition_results', to='pets.pet')),
                ('search_embedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='face_recognition.faceembedding')),
                ('searcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-search_timestamp', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='FaceDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_class', models.CharField(choices=[('cat_face', 'Cat Face'), ('dog_face', 'Dog Face'), ('cat', 'Cat'), ('dog', 'Dog')], max_length=20)),
                ('confidence', models.FloatField()),
                ('bounding_box', models.JSONField()),
                ('model_version', models.CharField(default='yolov8l', max_length=50)),
                ('detection_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('face_area', models.FloatField(blank=True, null=True)),
                ('face_quality_score', models.FloatField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='pets.petimage')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_images', models.IntegerField(default=0)),
                ('processed_images', models.IntegerField(default=0)),
                ('successful_embeddings', models.IntegerField(default=0)),
                ('failed_embeddings', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_jobs', to='pets.pet')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_jobs', to='pets.petregistrationsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
