# Generated by Django 4.2.7 on 2025-07-16 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProject',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('input_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_images', models.IntegerField(default=0)),
                ('faces_detected', models.IntegerField(default=0)),
                ('qr_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_vector', models.JSONField()),
                ('vector_dimension', models.IntegerField()),
                ('original_image_name', models.CharField(max_length=255)),
                ('face_crop_path', models.CharField(max_length=500)),
                ('confidence_score', models.FloatField()),
                ('bounding_box', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_vectors', to='simple_face_id.faceproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilaritySearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('best_match_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_face_id.faceproject')),
                ('best_match_vector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_face_id.facevector')),
            ],
        ),
    ]
